### ISSUE TITLE
Resnet50 的输出层的依据是什么?

### ISSUE THREAD

**Issue by jjjjohnson** [xiaomaxiao/PSENET#15]
大神好!
我看了backbone的输出层在[这里](https://github.com/xiaomaxiao/PSENET/blob/632ff98fe8dd1c7b9aad234698c8ee12b2227628/models/resnet.py#L32), 但是按照我的理解应该输出红框内的层 [pytorch 版本](https://github.com/jjjjohnson/PSENet.pytorch/blob/7b077cb7aa041ae44e0c7afacf5b3d3ef45047fb/models/resnet.py#L182)的应该就是这么输出层的, 能不能解释一下您找输出层的依据?:
![image](https://user-images.githubusercontent.com/20569095/71870321-7814df80-3150-11ea-8c82-42c8e59abf8d.png)
感激~

**Comment by xiaomaxiao** [comment]
你的输出是对的 ，取哪一层 ，我试验基本没什么影响。
