### ISSUE TITLE
每到训练第二个epoch，模型就出问题

### ISSUE THREAD

**Issue by HansRen1024** [xiaomaxiao/PSENET#16]
你好～我在训练自己的数据集。每次到第二个epoch，训练输出看着没问题，但是验证集结果有问题。我拿每个epoch的模型测试，没有输出结果。一直找不到原因。希望能听听您的建议。
训练输出：
Epoch 1/40
5241/5241 [==============================] - 9859s 2s/step - loss: 0.0084 - iou_bk: 0.9679 - iou_txt: 0.9900 - val_loss: 0.0232 - val_iou_bk: 0.8919 - val_iou_txt: 0.9692
Epoch 2/40
5241/5241 [==============================] - 9776s 2s/step - loss: 0.0048 - iou_bk: 0.9764 - iou_txt: 0.9933 - val_loss: 0.4221 - val_iou_bk: 0.2016 - val_iou_txt: 2.5102e-11
Epoch 3/40
5241/5241 [==============================] - 9777s 2s/step - loss: 0.0043 - iou_bk: 0.9769 - iou_txt: 0.9935 - val_loss: 0.4188 - val_iou_bk: 0.2016 - val_iou_txt: 2.5102e-11
Epoch 4/40
5241/5241 [==============================] - 9800s 2s/step - loss: 0.0042 - iou_bk: 0.9766 - iou_txt: 0.9934 - val_loss: 0.4159 - val_iou_bk: 0.2016 - val_iou_txt: 2.5103e-11
Epoch 5/40
5241/5241 [==============================] - 9760s 2s/step - loss: 0.0041 - iou_bk: 0.9763 - iou_txt: 0.9933 - val_loss: 0.4298 - val_iou_bk: 1.0210e-10 - val_iou_txt: 0.7984
Epoch 6/40
5241/5241 [==============================] - 9771s 2s/step - loss: 0.0041 - iou_bk: 0.9765 - iou_txt: 0.9934 - val_loss: 0.4283 - val_iou_bk: 1.0209e-10 - val_iou_txt: 0.7984

**Comment by HandsomeHans** [comment]
问题解决了，我是在提供的模型基础上finetune的，把学习率调低以后就好了。

**Comment by HansRen1024** [comment]
1. 降低了学习率，还是有问题。
2. 使用1%的数据集训练，没有问题。猜测有可能问题出现在数据集上。

**Comment by xiaomaxiao** [comment]
明显过拟合了

**Comment by HansRen1024** [comment]
@xiaomaxiao 我把训练集用来做验证，这样子训练集和验证集是一样的。也会出现上面的问题。所以应该不是过拟合。

**Comment by HansRen1024** [comment]
找到原因了，是数据集的问题。其中有一部分训练集图片导致的。奇怪我训练集和验证集都是自己统一生成的，为什么就那么几张出现了问题。
