### ISSUE TITLE
GPU利用率很低

### ISSUE THREAD

**Issue by cuppersd** [xiaomaxiao/PSENET#3]
您好，我在训练的时候GPU利用率特别低，有什么办法可以提高吗？

**Comment by xiaomaxiao** [comment]
可能是卡在io了

**Comment by hetianduan** [comment]
> 您好，我在训练的时候GPU利用率特别低，有什么办法可以提高吗？

你好 请问您解决了吗

**Comment by cuppersd** [comment]
> > 您好，我在训练的时候GPU利用率特别低，有什么办法可以提高吗？
> 
> 你好 请问您解决了吗

解决了

**Comment by hetianduan** [comment]
> 您好，我在训练的时候GPU利用率特别低，有什么办法可以提高吗？
> 
> 你好 请问您解决了吗
> 
> 解决了

你好 可以加一下我的VX 529744208吗？想请教您一下

**Comment by Lanme** [comment]
请问用什么数据集训练的？训练结果如何？

**Comment by cuppersd** [comment]
ICDAR2017+ICDAR2019+自己标注了一部分

**Comment by Lanme** [comment]
请问你跑预测的时候GPU有没有爆？就是我发现预测的时候GPU会增加图片内存，导致跑一百张就内存满了
