### ISSUE TITLE
predict.py里rects输出四个点，怎么输出旋转矩形的八个点呢？

### ISSUE THREAD

**Issue by unshaven** [xiaomaxiao/PSENET#9]
predict.py里rects输出四个点，怎么输出旋转矩形的八个点呢？

**Comment by Lanme** [comment]
请问你解决了么，这个输出的四个点应该只能检测水平文本而已

**Comment by xiaomaxiao** [comment]
> predict.py里rects输出四个点，怎么输出旋转矩形的八个点呢？

.ipynb 文件中有输出 旋转矩形的例子
